apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  selector:
    app: node-exporter  # Assuming this label is applied to your Node Exporter pods
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
