apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
    - name: node-exporter-port
      port: 9100
      targetPort: 9100
      nodePort: 31001