apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: prometheus-port
      port: 9090
      targetPort: 9090
      nodePort: 31000 # Choose a port number within the range of NodePort ports

